---
    server:
        port: 8848
        feRoot: '/root/project/output'
        update: '/root/project/update/img'

    database:
        dialect: mysql
        mysql:
            database: edit_system
            username: root
            password: ''
            port: 8306
            host: 127.0.0.1

    jwt:
        secret: edit-syetem
        key: jwt
        duration: '4h'
